plugins {
    id 'com.android.application'
}

android {
    namespace 'QiblaCompass.blackfalcon.jan'
    compileSdk 34

    defaultConfig {
        applicationId "QiblaCompass.blackfalcon.jan"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // APK file name: "QiblaCompass.apk"
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "QiblaCompass.apk"
        }
    }
}
